//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChoiseManagement.Models.Hotel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Event_GuestDetails
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Event_GuestDetails()
        {
            this.EventReservations = new HashSet<EventReservation>();
        }
    
        public int EventReservationId { get; set; }
        [DisplayName("Event Reservation ID")]
        public string GuestName { get; set; }
        [DisplayName("Guest Name")]
        public string Guest_Email { get; set; }
        [DisplayName("Guest Email")]
        public Nullable<int> Guest_Contact_No { get; set; }
        [DisplayName("Guest Contact Number")]
        public string EventName { get; set; }
        [DisplayName("Event Name")]
        public string EventDescription { get; set; }
        [DisplayName("Event Description")]

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventReservation> EventReservations { get; set; }
    }
}
