//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChoiseManagement.Models.Hotel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Food_Categories
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Food_Categories()
        {
            this.Food_Items = new HashSet<Food_Items>();
        }
    
        public int Food_category_Id { get; set; }
        [DisplayName("Food Category ID")]
        public string Category { get; set; }
        [DisplayName("Category")]
        public string Description { get; set; }
        [DisplayName("Description")]

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Food_Items> Food_Items { get; set; }
    }
}
