//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChoiseManagement.Models.Hotel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Food_Items
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Food_Items()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Item_Category_ID { get; set; }
        [DisplayName("Item Catagory ID")]
        public string Item_Name { get; set; }
        [DisplayName("Item ID")]
        public Nullable<int> Item_Code { get; set; }
        [DisplayName("Itam Code")]
        public string Description { get; set; }
        [DisplayName("Description")]
        public Nullable<int> Portion_Price { get; set; }
        [DisplayName("Portion Price")]
        public string Image_URL { get; set; }
        [DisplayName("Image URL")]

        public virtual Food_Categories Food_Categories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
    }
}
