//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChoiseManagement.Models.Hotel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Guest_Details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Guest_Details()
        {
            this.Reservations = new HashSet<Reservation>();
        }
    
        public int Guest_Id { get; set; }
        [DisplayName("ID")]
        public string Guest_Title { get; set; }
        [DisplayName("Title")]
        public string Guest_First_Name { get; set; }
        [DisplayName("First Name")]
        public string Guest_Last_Name { get; set; }
        [DisplayName("Last Name")]
        public string Guest_Address { get; set; }
        [DisplayName("Address")]
        public string Guest_Email { get; set; }
        [DisplayName("Email")]
        public string Guest_MobileNO { get; set; }
        [DisplayName("Mobile Number")]
        public string Paasword { get; set; }
        [DisplayName("Password")]

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reservation> Reservations { get; set; }
    }
}
