//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChoiseManagement.Models.Hotel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Hall
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hall()
        {
            this.EventReservations = new HashSet<EventReservation>();
        }
    
        public int HallId { get; set; }
        [DisplayName("Hall ID")]
        public string HallName { get; set; }
        [DisplayName("Hall Name")]
        public Nullable<int> HallCapacity { get; set; }
        [DisplayName("Hall Capacity")]
        public string HallDescription { get; set; }
        [DisplayName("Hall description")]
        public string HImage1 { get; set; }
        [DisplayName("Hall Image 1")]
        public string HImage2 { get; set; }
        [DisplayName("Hall Image 2")]
        public string HImage3 { get; set; }
        [DisplayName("Hall Image 3")]
        public string HImage4 { get; set; }
        [DisplayName("Hall Image 4")]
        public Nullable<int> Hall_price_Hour { get; set; }
        [DisplayName("Hall Price/hour")]

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventReservation> EventReservations { get; set; }
    }
}
