//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChoiseManagement.Models.Hotel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Reservation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reservation()
        {
            this.Orders = new HashSet<Order>();
            this.RoomBookings = new HashSet<RoomBooking>();
        }
    
        public int Reservation_Id { get; set; }
        [DisplayName("Reservation ID")]
        public Nullable<int> Guest_Id { get; set; }
        [DisplayName("Guest ID")]
        public Nullable<int> Package_Id { get; set; }
        [DisplayName("Package ID")]
        public Nullable<int> Room_Number { get; set; }
        [DisplayName("Room Number")]
        public Nullable<System.DateTime> Check_In { get; set; }
        [DisplayName("Check IN")]
        public Nullable<System.DateTime> Check_Out { get; set; }
        [DisplayName("Check OUT")]
        public Nullable<int> Adults { get; set; }
        [DisplayName("Adults")]
        public Nullable<int> Childrens { get; set; }
        [DisplayName("Children")]

        public virtual Guest_Details Guest_Details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
        public virtual Package Package { get; set; }
        public virtual Room Room { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoomBooking> RoomBookings { get; set; }
    }
}
