//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChoiseManagement.Models.Hotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Room()
        {
            this.Reservations = new HashSet<Reservation>();
        }
    
        public int Room_Id { get; set; }
        public Nullable<int> Room_Category_Id { get; set; }
        public Nullable<int> Room_Number { get; set; }
        public string Room_Description { get; set; }
        public string Room_Image_url_1 { get; set; }
        public string Room_Image_url_2 { get; set; }
        public string Room_Image_url_3 { get; set; }
        public string Room_Image_url_4 { get; set; }
        public string Room_Image_url_5 { get; set; }
        public Nullable<int> RoomCapacity { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reservation> Reservations { get; set; }
        public virtual Room_Catagorys Room_Catagorys { get; set; }
    }
}
