//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChoiseManagement.Models.Hotel
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class RoomBooking
    {
        public int BookingID { get; set; }
        [DisplayName("Booking ID")]
        public Nullable<int> RoomNo { get; set; }
        [DisplayName("Room Number")]
        public Nullable<int> CategoryId { get; set; }
        [DisplayName("Category ID")]
        public Nullable<System.DateTime> ArivalDate { get; set; }
        [DisplayName("Arrival Date")]
        public Nullable<System.DateTime> DepartureDate { get; set; }
        [DisplayName("Departure Date")]
        public int ReservationId { get; set; }
        [DisplayName("Reservation ID")]

        public virtual Reservation Reservation { get; set; }
    }
}
